theme: jekyll-theme-hacker
title: Welcome to Shivam's Website !
description: This website is developed for my family and friends, so that they get their memories(pics) with me anytime and anywhere without doing the hell of search around the many thousands of pics. 
